using MarquitoUtils.Main.Common.Enums;
using MarquitoUtils.MAUI.Common.Attributes;

namespace MarquitoUtils.MAUI.Common.Enums
{
    public enum Icon
    {
        #region Icones

        [Icon("e900")]
        HOME,
        [Icon("e901")]
        HOME2,
        [Icon("e902")]
        HOME3,
        [Icon("e903")]
        OFFICE,
        [Icon("e904")]
        NEWSPAPER,
        [Icon("e905")]
        PENCIL,
        [Icon("e906")]
        PENCIL2,
        [Icon("e907")]
        QUILL,
        [Icon("e908")]
        PEN,
        [Icon("e909")]
        BLOG,
        [Icon("e90a")]
        EYEDROPPER,
        [Icon("e90b")]
        DROPLET,
        [Icon("e90c")]
        PAINT_FORMAT,
        [Icon("e90d")]
        IMAGE,
        [Icon("e90e")]
        IMAGES,
        [Icon("e90f")]
        CAMERA,
        [Icon("e910")]
        HEADPHONES,
        [Icon("e911")]
        MUSIC,
        [Icon("e912")]
        PLAY,
        [Icon("e913")]
        FILM,
        [Icon("e914")]
        VIDEO_CAMERA,
        [Icon("e915")]
        DICE,
        [Icon("e916")]
        PACMAN,
        [Icon("e917")]
        SPADES,
        [Icon("e918")]
        CLUBS,
        [Icon("e919")]
        DIAMONDS,
        [Icon("e91a")]
        BULLHORN,
        [Icon("e91b")]
        CONNECTION,
        [Icon("e91c")]
        PODCAST,
        [Icon("e91d")]
        FEED,
        [Icon("e91e")]
        MIC,
        [Icon("e91f")]
        BOOK,
        [Icon("e920")]
        BOOKS,
        [Icon("e921")]
        LIBRARY,
        [Icon("e922")]
        FILE_TEXT,
        [Icon("e923")]
        PROFILE,
        [Icon("e924")]
        FILE_EMPTY,
        [Icon("e925")]
        FILES_EMPTY,
        [Icon("e926")]
        FILE_TEXT2,
        [Icon("e927")]
        FILE_PICTURE,
        [Icon("e928")]
        FILE_MUSIC,
        [Icon("e929")]
        FILE_PLAY,
        [Icon("e92a")]
        FILE_VIDEO,
        [Icon("e92b")]
        FILE_ZIP,
        [Icon("e92c")]
        COPY,
        [Icon("e92d")]
        PASTE,
        [Icon("e92e")]
        STACK,
        [Icon("e92f")]
        FOLDER,
        [Icon("e930")]
        FOLDER_OPEN,
        [Icon("e931")]
        FOLDER_PLUS,
        [Icon("e932")]
        FOLDER_MINUS,
        [Icon("e933")]
        FOLDER_DOWNLOAD,
        [Icon("e934")]
        FOLDER_UPLOAD,
        [Icon("e935")]
        PRICE_TAG,
        [Icon("e936")]
        PRICE_TAGS,
        [Icon("e937")]
        BARCODE,
        [Icon("e938")]
        QRCODE,
        [Icon("e939")]
        TICKET,
        [Icon("e93a")]
        CART,
        [Icon("e93b")]
        COIN_DOLLAR,
        [Icon("e93c")]
        COIN_EURO,
        [Icon("e93d")]
        COIN_POUND,
        [Icon("e93e")]
        COIN_YEN,
        [Icon("e93f")]
        CREDIT_CARD,
        [Icon("e940")]
        CALCULATOR,
        [Icon("e941")]
        LIFEBUOY,
        [Icon("e942")]
        PHONE,
        [Icon("e943")]
        PHONE_HANG_UP,
        [Icon("e944")]
        ADDRESS_BOOK,
        [Icon("e945")]
        ENVELOP,
        [Icon("e946")]
        PUSHPIN,
        [Icon("e947")]
        LOCATION,
        [Icon("e948")]
        LOCATION2,
        [Icon("e949")]
        COMPASS,
        [Icon("e94a")]
        COMPASS2,
        [Icon("e94b")]
        MAP,
        [Icon("e94c")]
        MAP2,
        [Icon("e94d")]
        HISTORY,
        [Icon("e94e")]
        CLOCK,
        [Icon("e94f")]
        CLOCK2,
        [Icon("e950")]
        ALARM,
        [Icon("e951")]
        BELL,
        [Icon("e952")]
        STOPWATCH,
        [Icon("e953")]
        CALENDAR,
        [Icon("e954")]
        PRINTER,
        [Icon("e955")]
        KEYBOARD,
        [Icon("e956")]
        DISPLAY,
        [Icon("e957")]
        LAPTOP,
        [Icon("e958")]
        MOBILE,
        [Icon("e959")]
        MOBILE2,
        [Icon("e95a")]
        TABLET,
        [Icon("e95b")]
        TV,
        [Icon("e95c")]
        DRAWER,
        [Icon("e95d")]
        DRAWER2,
        [Icon("e95e")]
        BOX_ADD,
        [Icon("e95f")]
        BOX_REMOVE,
        [Icon("e960")]
        DOWNLOAD,
        [Icon("e961")]
        UPLOAD,
        [Icon("e962")]
        FLOPPY_DISK,
        [Icon("e963")]
        DRIVE,
        [Icon("e964")]
        DATABASE,
        [Icon("e965")]
        UNDO,
        [Icon("e966")]
        REDO,
        [Icon("e967")]
        UNDO2,
        [Icon("e968")]
        REDO2,
        [Icon("e969")]
        FORWARD,
        [Icon("e96a")]
        REPLY,
        [Icon("e96b")]
        BUBBLE,
        [Icon("e96c")]
        BUBBLES,
        [Icon("e96d")]
        BUBBLES2,
        [Icon("e96e")]
        BUBBLE2,
        [Icon("e96f")]
        BUBBLES3,
        [Icon("e970")]
        BUBBLES4,
        [Icon("e971")]
        USER,
        [Icon("e972")]
        USERS,
        [Icon("e973")]
        USER_PLUS,
        [Icon("e974")]
        USER_MINUS,
        [Icon("e975")]
        USER_CHECK,
        [Icon("e976")]
        USER_TIE,
        [Icon("e977")]
        QUOTES_LEFT,
        [Icon("e978")]
        QUOTES_RIGHT,
        [Icon("e979")]
        HOUR_GLASS,
        [Icon("e97a")]
        SPINNER,
        [Icon("e97b")]
        SPINNER2,
        [Icon("e97c")]
        SPINNER3,
        [Icon("e97d")]
        SPINNER4,
        [Icon("e97e")]
        SPINNER5,
        [Icon("e97f")]
        SPINNER6,
        [Icon("e980")]
        SPINNER7,
        [Icon("e981")]
        SPINNER8,
        [Icon("e982")]
        SPINNER9,
        [Icon("e983")]
        SPINNER10,
        [Icon("e984")]
        SPINNER11,
        [Icon("e985")]
        BINOCULARS,
        [Icon("e986")]
        SEARCH,
        [Icon("e987")]
        ZOOM_IN,
        [Icon("e988")]
        ZOOM_OUT,
        [Icon("e989")]
        ENLARGE,
        [Icon("e98a")]
        SHRINK,
        [Icon("e98b")]
        ENLARGE2,
        [Icon("e98c")]
        SHRINK2,
        [Icon("e98d")]
        KEY,
        [Icon("e98e")]
        KEY2,
        [Icon("e98f")]
        LOCK,
        [Icon("e990")]
        UNLOCKED,
        [Icon("e991")]
        WRENCH,
        [Icon("e992")]
        EQUALIZER,
        [Icon("e993")]
        EQUALIZER2,
        [Icon("e994")]
        COG,
        [Icon("e995")]
        COGS,
        [Icon("e996")]
        HAMMER,
        [Icon("e997")]
        MAGIC_WAND,
        [Icon("e998")]
        AID_KIT,
        [Icon("e999")]
        BUG,
        [Icon("e99a")]
        PIE_CHART,
        [Icon("e99b")]
        STATS_DOTS,
        [Icon("e99c")]
        STATS_BARS,
        [Icon("e99d")]
        STATS_BARS2,
        [Icon("e99e")]
        TROPHY,
        [Icon("e99f")]
        GIFT,
        [Icon("e9a0")]
        GLASS,
        [Icon("e9a1")]
        GLASS2,
        [Icon("e9a2")]
        MUG,
        [Icon("e9a3")]
        SPOON_KNIFE,
        [Icon("e9a4")]
        LEAF,
        [Icon("e9a5")]
        ROCKET,
        [Icon("e9a6")]
        METER,
        [Icon("e9a7")]
        METER2,
        [Icon("e9a8")]
        HAMMER2,
        [Icon("e9a9")]
        FIRE,
        [Icon("e9aa")]
        LAB,
        [Icon("e9ab")]
        MAGNET,
        [Icon("e9ac")]
        BIN,
        [Icon("e9ad")]
        BIN2,
        [Icon("e9ae")]
        BRIEFCASE,
        [Icon("e9af")]
        AIRPLANE,
        [Icon("e9b0")]
        TRUCK,
        [Icon("e9b1")]
        ROAD,
        [Icon("e9b2")]
        ACCESSIBILITY,
        [Icon("e9b3")]
        TARGET,
        [Icon("e9b4")]
        SHIELD,
        [Icon("e9b5")]
        POWER,
        [Icon("e9b6")]
        SWITCH,
        [Icon("e9b7")]
        POWER_CORD,
        [Icon("e9b8")]
        CLIPBOARD,
        [Icon("e9b9")]
        LIST_NUMBERED,
        [Icon("e9ba")]
        LIST,
        [Icon("e9bb")]
        LIST2,
        [Icon("e9bc")]
        TREE,
        [Icon("e9bd")]
        MENU,
        [Icon("e9be")]
        MENU2,
        [Icon("e9bf")]
        MENU3,
        [Icon("e9c0")]
        MENU4,
        [Icon("e9c1")]
        CLOUD,
        [Icon("e9c2")]
        CLOUD_DOWNLOAD,
        [Icon("e9c3")]
        CLOUD_UPLOAD,
        [Icon("e9c4")]
        CLOUD_CHECK,
        [Icon("e9c5")]
        DOWNLOAD2,
        [Icon("e9c6")]
        UPLOAD2,
        [Icon("e9c7")]
        DOWNLOAD3,
        [Icon("e9c8")]
        UPLOAD3,
        [Icon("e9c9")]
        SPHERE,
        [Icon("e9ca")]
        EARTH,
        [Icon("e9cb")]
        LINK,
        [Icon("e9cc")]
        FLAG,
        [Icon("e9cd")]
        ATTACHMENT,
        [Icon("e9ce")]
        EYE,
        [Icon("e9cf")]
        EYE_PLUS,
        [Icon("e9d0")]
        EYE_MINUS,
        [Icon("e9d1")]
        EYE_BLOCKED,
        [Icon("e9d2")]
        BOOKMARK,
        [Icon("e9d3")]
        BOOKMARKS,
        [Icon("e9d4")]
        SUN,
        [Icon("e9d5")]
        CONTRAST,
        [Icon("e9d6")]
        BRIGHTNESS_CONTRAST,
        [Icon("e9d7")]
        STAR_EMPTY,
        [Icon("e9d8")]
        STAR_HALF,
        [Icon("e9d9")]
        STAR_FULL,
        [Icon("e9da")]
        HEART,
        [Icon("e9db")]
        HEART_BROKEN,
        [Icon("e9dc")]
        MAN,
        [Icon("e9dd")]
        WOMAN,
        [Icon("e9de")]
        MAN_WOMAN,
        [Icon("e9df")]
        HAPPY,
        [Icon("e9e0")]
        HAPPY2,
        [Icon("e9e1")]
        SMILE,
        [Icon("e9e2")]
        SMILE2,
        [Icon("e9e3")]
        TONGUE,
        [Icon("e9e4")]
        TONGUE2,
        [Icon("e9e5")]
        SAD,
        [Icon("e9e6")]
        SAD2,
        [Icon("e9e7")]
        WINK,
        [Icon("e9e8")]
        WINK2,
        [Icon("e9e9")]
        GRIN,
        [Icon("e9ea")]
        GRIN2,
        [Icon("e9eb")]
        COOL,
        [Icon("e9ec")]
        COOL2,
        [Icon("e9ed")]
        ANGRY,
        [Icon("e9ee")]
        ANGRY2,
        [Icon("e9ef")]
        EVIL,
        [Icon("e9f0")]
        EVIL2,
        [Icon("e9f1")]
        SHOCKED,
        [Icon("e9f2")]
        SHOCKED2,
        [Icon("e9f3")]
        BAFFLED,
        [Icon("e9f4")]
        BAFFLED2,
        [Icon("e9f5")]
        CONFUSED,
        [Icon("e9f6")]
        CONFUSED2,
        [Icon("e9f7")]
        NEUTRAL,
        [Icon("e9f8")]
        NEUTRAL2,
        [Icon("e9f9")]
        HIPSTER,
        [Icon("e9fa")]
        HIPSTER2,
        [Icon("e9fb")]
        WONDERING,
        [Icon("e9fc")]
        WONDERING2,
        [Icon("e9fd")]
        SLEEPY,
        [Icon("e9fe")]
        SLEEPY2,
        [Icon("e9ff")]
        FRUSTRATED,
        [Icon("ea00")]
        FRUSTRATED2,
        [Icon("ea01")]
        CRYING,
        [Icon("ea02")]
        CRYING2,
        [Icon("ea03")]
        POINT_UP,
        [Icon("ea04")]
        POINT_RIGHT,
        [Icon("ea05")]
        POINT_DOWN,
        [Icon("ea06")]
        POINT_LEFT,
        [Icon("ea07")]
        WARNING,
        [Icon("ea08")]
        NOTIFICATION,
        [Icon("ea09")]
        QUESTION,
        [Icon("ea0a")]
        PLUS,
        [Icon("ea0b")]
        MINUS,
        [Icon("ea0c")]
        INFO,
        [Icon("ea0d")]
        CANCEL_CIRCLE,
        [Icon("ea0e")]
        BLOCKED,
        [Icon("ea0f")]
        CROSS,
        [Icon("ea10")]
        CHECKMARK,
        [Icon("ea11")]
        CHECKMARK2,
        [Icon("ea12")]
        SPELL_CHECK,
        [Icon("ea13")]
        ENTER,
        [Icon("ea14")]
        EXIT,
        [Icon("ea15")]
        PLAY2,
        [Icon("ea16")]
        PAUSE,
        [Icon("ea17")]
        STOP,
        [Icon("ea18")]
        PREVIOUS,
        [Icon("ea19")]
        NEXT,
        [Icon("ea1a")]
        BACKWARD,
        [Icon("ea1b")]
        FORWARD2,
        [Icon("ea1c")]
        PLAY3,
        [Icon("ea1d")]
        PAUSE2,
        [Icon("ea1e")]
        STOP2,
        [Icon("ea1f")]
        BACKWARD2,
        [Icon("ea20")]
        FORWARD3,
        [Icon("ea21")]
        FIRST,
        [Icon("ea22")]
        LAST,
        [Icon("ea23")]
        PREVIOUS2,
        [Icon("ea24")]
        NEXT2,
        [Icon("ea25")]
        EJECT,
        [Icon("ea26")]
        VOLUME_HIGH,
        [Icon("ea27")]
        VOLUME_MEDIUM,
        [Icon("ea28")]
        VOLUME_LOW,
        [Icon("ea29")]
        VOLUME_MUTE,
        [Icon("ea2a")]
        VOLUME_MUTE2,
        [Icon("ea2b")]
        VOLUME_INCREASE,
        [Icon("ea2c")]
        VOLUME_DECREASE,
        [Icon("ea2d")]
        LOOP,
        [Icon("ea2e")]
        LOOP2,
        [Icon("ea2f")]
        INFINITE,
        [Icon("ea30")]
        SHUFFLE,
        [Icon("ea31")]
        ARROW_UP_LEFT,
        [Icon("ea32")]
        ARROW_UP,
        [Icon("ea33")]
        ARROW_UP_RIGHT,
        [Icon("ea34")]
        ARROW_RIGHT,
        [Icon("ea35")]
        ARROW_DOWN_RIGHT,
        [Icon("ea36")]
        ARROW_DOWN,
        [Icon("ea37")]
        ARROW_DOWN_LEFT,
        [Icon("ea38")]
        ARROW_LEFT,
        [Icon("ea39")]
        ARROW_UP_LEFT2,
        [Icon("ea3a")]
        ARROW_UP2,
        [Icon("ea3b")]
        ARROW_UP_RIGHT2,
        [Icon("ea3c")]
        ARROW_RIGHT2,
        [Icon("ea3d")]
        ARROW_DOWN_RIGHT2,
        [Icon("ea3e")]
        ARROW_DOWN2,
        [Icon("ea3f")]
        ARROW_DOWN_LEFT2,
        [Icon("ea40")]
        ARROW_LEFT2,
        [Icon("ea41")]
        CIRCLE_UP,
        [Icon("ea42")]
        CIRCLE_RIGHT,
        [Icon("ea43")]
        CIRCLE_DOWN,
        [Icon("ea44")]
        CIRCLE_LEFT,
        [Icon("ea45")]
        TAB,
        [Icon("ea46")]
        MOVE_UP,
        [Icon("ea47")]
        MOVE_DOWN,
        [Icon("ea48")]
        SORT_ALPHA_ASC,
        [Icon("ea49")]
        SORT_ALPHA_DESC,
        [Icon("ea4a")]
        SORT_NUMERIC_ASC,
        [Icon("ea4b")]
        SORT_NUMBERIC_DESC,
        [Icon("ea4c")]
        SORT_AMOUNT_ASC,
        [Icon("ea4d")]
        SORT_AMOUNT_DESC,
        [Icon("ea4e")]
        COMMAND,
        [Icon("ea4f")]
        SHIFT,
        [Icon("ea50")]
        CTRL,
        [Icon("ea51")]
        OPT,
        [Icon("ea52")]
        CHECKBOX_CHECKED,
        [Icon("ea53")]
        CHECKBOX_UNCHECKED,
        [Icon("ea54")]
        RADIO_CHECKED,
        [Icon("ea55")]
        RADIO_CHECKED2,
        [Icon("ea56")]
        RADIO_UNCHECKED,
        [Icon("ea57")]
        CROP,
        [Icon("ea58")]
        MAKE_GROUP,
        [Icon("ea59")]
        UNGROUP,
        [Icon("ea5a")]
        SCISSORS,
        [Icon("ea5b")]
        FILTER,
        [Icon("ea5c")]
        FONT,
        [Icon("ea5d")]
        LIGATURE,
        [Icon("ea5e")]
        LIGATURE2,
        [Icon("ea5f")]
        TEXT_HEIGHT,
        [Icon("ea60")]
        TEXT_WIDTH,
        [Icon("ea61")]
        FONT_SIZE,
        [Icon("ea62")]
        BOLD,
        [Icon("ea63")]
        UNDERLINE,
        [Icon("ea64")]
        ITALIC,
        [Icon("ea65")]
        STRIKETHROUGH,
        [Icon("ea66")]
        OMEGA,
        [Icon("ea67")]
        SIGMA,
        [Icon("ea68")]
        PAGE_BREAK,
        [Icon("ea69")]
        SUPERSCRIPT,
        [Icon("ea6a")]
        SUBSCRIPT,
        [Icon("ea6b")]
        SUPERSCRIPT2,
        [Icon("ea6c")]
        SUBSCRIPT2,
        [Icon("ea6d")]
        TEXT_COLOR,
        [Icon("ea6e")]
        PAGEBREAK,
        [Icon("ea6f")]
        CLEAR_FORMATTING,
        [Icon("ea70")]
        TABLE,
        [Icon("ea71")]
        TABLE2,
        [Icon("ea72")]
        INSERT_TEMPLATE,
        [Icon("ea73")]
        PILCROW,
        [Icon("ea74")]
        LTR,
        [Icon("ea75")]
        RTL,
        [Icon("ea76")]
        SECTION,
        [Icon("ea77")]
        PARAGRAPH_LEFT,
        [Icon("ea78")]
        PARAGRAPH_CENTER,
        [Icon("ea79")]
        PARAGRAPH_RIGHT,
        [Icon("ea7a")]
        PARAGRAPH_JUSTIFY,
        [Icon("ea7b")]
        INDENT_INCREASE,
        [Icon("ea7c")]
        INDENT_DECREASE,
        [Icon("ea7d")]
        SHARE,
        [Icon("ea7e")]
        NEW_TAB,
        [Icon("ea7f")]
        EMBED,
        [Icon("ea80")]
        EMBED2,
        [Icon("ea81")]
        TERMINAL,
        [Icon("ea82")]
        SHARE2,
        [Icon("ea83")]
        MAIL,
        [Icon("ea84")]
        MAIL2,
        [Icon("ea85")]
        MAIL3,
        [Icon("ea86")]
        MAIL4,
        [Icon("ea87")]
        AMAZON,
        [Icon("ea88")]
        GOOGLE,
        [Icon("ea89")]
        GOOGLE2,
        [Icon("ea8a")]
        GOOGLE3,
        [Icon("ea8b")]
        GOOGLE_PLUS,
        [Icon("ea8c")]
        GOOGLE_PLUS2,
        [Icon("ea8d")]
        GOOGLE_PLUS3,
        [Icon("ea8e")]
        HANGOUTS,
        [Icon("ea8f")]
        GOOGLE_DRIVE,
        [Icon("ea90")]
        FACEBOOK,
        [Icon("ea91")]
        FACEBOOK2,
        [Icon("ea92")]
        INSTAGRAM,
        [Icon("ea93")]
        WHATSAPP,
        [Icon("ea94")]
        SPOTIFY,
        [Icon("ea95")]
        TELEGRAM,
        [Icon("ea96")]
        TWITTER,
        [Icon("ea97")]
        VINE,
        [Icon("ea98")]
        VK,
        [Icon("ea99")]
        RENREN,
        [Icon("ea9a")]
        SINA_WEIBO,
        [Icon("ea9b")]
        RSS,
        [Icon("ea9c")]
        RSS2,
        [Icon("ea9d")]
        YOUTUBE,
        [Icon("ea9e")]
        YOUTUBE2,
        [Icon("ea9f")]
        TWITCH,
        [Icon("eaa0")]
        VIMEO,
        [Icon("eaa1")]
        VIMEO2,
        [Icon("eaa2")]
        LANYRD,
        [Icon("eaa3")]
        FLICKR,
        [Icon("eaa4")]
        FLICKR2,
        [Icon("eaa5")]
        FLICKR3,
        [Icon("eaa6")]
        FLICKR4,
        [Icon("eaa7")]
        DRIBBBLE,
        [Icon("eaa8")]
        BEHANCE,
        [Icon("eaa9")]
        BEHANCE2,
        [Icon("eaaa")]
        DEVIANTART,
        [Icon("eaab")]
        PX500,
        [Icon("eaac")]
        STEAM,
        [Icon("eaad")]
        STEAM2,
        [Icon("eaae")]
        DROPBOX,
        [Icon("eaaf")]
        ONEDRIVE,
        [Icon("eab0")]
        GITHUB,
        [Icon("eab1")]
        NPM,
        [Icon("eab2")]
        BASECAMP,
        [Icon("eab3")]
        TRELLO,
        [Icon("eab4")]
        WORDPRESS,
        [Icon("eab5")]
        JOOMLA,
        [Icon("eab6")]
        ELLO,
        [Icon("eab7")]
        BLOGGER,
        [Icon("eab8")]
        BLOGGER2,
        [Icon("eab9")]
        TUMBLR,
        [Icon("eaba")]
        TUMBLR2,
        [Icon("eabb")]
        YAHOO,
        [Icon("eabc")]
        YAHOO2,
        [Icon("eabd")]
        TUX,
        [Icon("eabe")]
        APPLEINC,
        [Icon("eabf")]
        FINDER,
        [Icon("eac0")]
        ANDROID,
        [Icon("eac1")]
        WINDOWS,
        [Icon("eac2")]
        WINDOWS8,
        [Icon("eac3")]
        SOUNDCLOUD,
        [Icon("eac4")]
        SOUNDCLOUD2,
        [Icon("eac5")]
        SKYPE,
        [Icon("eac6")]
        REDDIT,
        [Icon("eac7")]
        HACKERNEWS,
        [Icon("eac8")]
        WIKIPEDIA,
        [Icon("eac9")]
        LINKEDIN,
        [Icon("eaca")]
        LINKEDIN2,
        [Icon("eacb")]
        LASTFM,
        [Icon("eacc")]
        LASTFM2,
        [Icon("eacd")]
        DELICIOUS,
        [Icon("eace")]
        STUMBLEUPON,
        [Icon("eacf")]
        STUMBLEUPON2,
        [Icon("ead0")]
        STACKOVERFLOW,
        [Icon("ead1")]
        PINTEREST,
        [Icon("ead2")]
        PINTEREST2,
        [Icon("ead3")]
        XING,
        [Icon("ead4")]
        XING2,
        [Icon("ead5")]
        FLATTR,
        [Icon("ead6")]
        FOURSQUARE,
        [Icon("ead7")]
        YELP,
        [Icon("ead8")]
        PAYPAL,
        [Icon("ead9")]
        CHROME,
        [Icon("eada")]
        FIREFOX,
        [Icon("eadb")]
        IE,
        [Icon("eadc")]
        EDGE,
        [Icon("eadd")]
        SAFARI,
        [Icon("eade")]
        OPERA,
        [Icon("eadf")]
        FILE_PDF,
        [Icon("eae0")]
        FILE_OPENOFFICE,
        [Icon("eae1")]
        FILE_WORD,
        [Icon("eae2")]
        FILE_EXCEL,
        [Icon("eae3")]
        LIBREOFFICE,
        [Icon("eae4")]
        HTML_FIVE,
        [Icon("eae5")]
        HTML_FIVE2,
        [Icon("eae6")]
        CSS3,
        [Icon("eae7")]
        GIT,
        [Icon("eae8")]
        CODEPEN,
        [Icon("eae9")]
        SVG,
        [Icon("eaea")]
        ICOMOON,

        #endregion Icones
    }

    public static class IconExtensions
    {
        public static string GetIconCode(this Icon icon)
        {
            return icon.GetAttribute<IconAttribute, Icon>().IconCode;
        }

        public static string GetIconUniCodeCharacter(this Icon icon)
        {
            string? hex = icon.GetIconCode();

            if (!string.IsNullOrEmpty(hex) && int.TryParse(hex, System.Globalization.NumberStyles.HexNumber, null, out int codePoint))
            {
                // Convert the hex code (e.g. "e972") into the actual Unicode character so the font glyph renders.
                return char.ConvertFromUtf32(codePoint);
            }
            else
            {
                return string.Empty;
            }
        }
    }
}
